nodeLinker: node-modules

npmScopes:
  touchto:
    npmRegistryServer: 'https://registry.touchto.io'

# plugins:
#   - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
#     spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
